### ISSUE TITLE
Support Item page - data import & presentation issues

### ISSUE THREAD

**Issue by onthebreeze** [gs-ndis/emarket#10]
I think we have "Location" in the wrong place.  There are many spreadsheet at https://www.ndis.gov.au/providers/pricing-and-payment.html.  All have the same variant IDs but have different prices.  Therefore our model needs to change as documented at https://github.com/gs-ndis/emarket/blob/master/docs/SupportItemsAndVariants.md - please look at the "priceCaps" entity and sample JSON.

Also, it looks like there's something wrong with the data import logic because priced items in the source spreadsheet are showing as non-priced after import.
![supportitempagefixes](https://cloud.githubusercontent.com/assets/13426392/20546703/273cff7e-b16b-11e6-9ecb-1d32d9dbb4df.png)
![self care activities with price cap](https://cloud.githubusercontent.com/assets/13426392/20546704/273f1a2a-b16b-11e6-9a76-c3bda9f6e62e.png)

**Comment by limit85** [comment]
Resolved in 21a728a
