### ISSUE TITLE
Create mockups for support item catalog.

### ISSUE THREAD

**Issue by onthebreeze** [gs-ndis/emarket#5]
Please refer to the [wireframes](https://github.com/gs-ndis/emarket/blob/master/docs/SupportItemsAndVariants.md) and create mockups accordingly.  

Also please take a look at https://www.ndis.gov.au/ for a bit of guidance on theme.

**Comment by onthebreeze** [comment]
![support-item-details](https://cloud.githubusercontent.com/assets/13426392/20034298/1bc1325c-a40d-11e6-9b2b-3f46034b1468.jpg)

Good work fritz.  Comments added to the mockup.

**Comment by onthebreeze** [comment]
The home page and search results mockups are fine (maybe add the "welcome 'name' 'role'" text and logout button.

Please upload PSD for all so that Alex can get on with implementation.
![search-result](https://cloud.githubusercontent.com/assets/13426392/20034308/74944c7a-a40d-11e6-98eb-a5a37086cc5f.jpg)
![home](https://cloud.githubusercontent.com/assets/13426392/20034309/74962cfc-a40d-11e6-856e-89e714a54cad.jpg)

**Comment by fritzelemino** [comment]
Hi @onthebreeze , please check the PSDs and the updated versions here:

https://www.dropbox.com/sh/wdoj1el56bpul58/AAD0oIgpjFhuSKpzrBtGxIhWa?dl=0

Let me know your thoughts

Regards,

**Comment by onthebreeze** [comment]
All good.   Thanks for your work.

Alex - please implement.
