### ISSUE TITLE
Create MEAN stack dev server

### ISSUE THREAD

**Issue by onthebreeze** [gs-ndis/emarket#6]
Please spin up a MEAN stack server - Marketplace AMI will be fine.  t2.small probably ok.

Provide SSH credentials to @limit85

**Comment by onthebreeze** [comment]
and please update this ticket with public IP / AWS domain name so I can create a DNS entry to point catalog-alpha.showthething.com to it

**Comment by limit85** [comment]
project is deployed and configured on server http://ec2-52-62-172-42.ap-southeast-2.compute.amazonaws.com/
alias
http://catalog-alpha.showthething.com/

temporary admin login/pass is 
admin@admin.com / admin
